@isTest(SeeAllData=true)
public class RHX_TEST_OrderItem {
    static testMethod void RHX_Testmethod() {
        List<sObject> sourceList = [SELECT Id 
            FROM OrderItem order by lastmodifieddate desc LIMIT 1];
        if(sourceList.size() == 0) {
            sourceList.add(
                    new OrderItem()
            );
        }
        rh2.ParentUtil.UpsertRollupTestRecords( sourceList );
    }
}