@isTest(SeeAllData=true)

public class RHX_TEST_FKT_Quote {

 static testMethod void RHX_Testmethod() {

       List<sObject> sourceList = [SELECT Id

     FROM Quote ORDER BY LastModifiedDate DESC LIMIT 1];

       if(sourceList.size() == 0) {

           sourceList.add(

                   new Quote()

           );

       }

     rh2.ParentUtil.UpsertRollupTestRecords( sourceList );

//Only apply when code coverage needed

Sobject testdel = [SELECT Id FROM Quote ORDER BY LastModifiedDate DESC LIMIT 1];

delete(testdel);

   }

 

}